### ISSUE TITLE
"For enterprise subscribers" badge completely hides the column header at some viewport widths

### ISSUE THREAD

**Issue by Haprog** [qtdzz/vaadin-platform-versions#10]
![image](https://user-images.githubusercontent.com/75155/78327497-b110f480-7585-11ea-9564-ad0fc0d15cd7.png)

**Comment by qtdzz** [comment]
Hi Kari, thank you for creating the issue. Unfortunately, I don't have time and interest in this project anymore. I am going to archive this repository. Please feel free to clone the code if you still find it useful.

Regards,
Tien.
