### ISSUE TITLE
Make it easier see the differences between versions

### ISSUE THREAD

**Issue by johannesh2** [qtdzz/vaadin-platform-versions#2]
An improvement suggestion: it would be nice to spot the difference easier between two/more Vaadin versions. One idea could be to have the items display differently when the versions are same:

![image](https://user-images.githubusercontent.com/1398470/55402323-dc6c9800-555b-11e9-89e7-81c665f3f045.png)

Maybe there could be a enable diff checkbox etc. to toggle this behavior.

**Comment by qtdzz** [comment]
Thank you for the suggestion. I implemented and deployed.
From commit: https://github.com/qtdzz/vaadin-platform-versions/commit/272d0c323580dd3ce37f3cf98aa4d662daff8d1f
