### ISSUE TITLE
Make it easy to see when the info in a column has updated after selecting another version for a column

### ISSUE THREAD

**Issue by Haprog** [qtdzz/vaadin-platform-versions#8]
Sometimes it can be slow to update (e.g. if you're on slow connection) when you select a platform version for a column you can't see if it's still loading info or is it showing wrong info (of previously selected version) before it has updated so it's hard to see has the info been loaded or not (especially when you switch between versions that don't have many differences).

It would be much better if it would clear the old info from the column immediately when you select a new version for the column. Then you would clearly see when the new info has loaded.

Maybe include an additional loading indicator for a column (or a global loading indicator to show if some data is still loading).

**Comment by qtdzz** [comment]
Hi @Haprog , thank you for writing up these issues. I really appreciate it. Unfortunately, I don't think now I have enough time to continue maintaining and developing this project. If you have interests, I can transfer this to you and remove the herokuapp, so you can take the same domain name as it is right now. Please let me know. Thank you!

**Comment by Haprog** [comment]
Unfortunately I don't have much time either so I can't commit to any proper maintenance/development. I might be able to do small contributions/PRs once in a while though.

**Comment by qtdzz** [comment]
Hi Kari, thank you for create the issue. Unfortunately, I don't have time and interest in this project anymore. I am going to archive this repository. Please feel free to clone the code if you still find it useful.

Regards,
Tien.
