### ISSUE TITLE
Roadmap page shows incorrect or confusing info for General Availability and maybe other dates

### ISSUE THREAD

**Issue by Haprog** [qtdzz/vaadin-platform-versions#9]
[General Availability](https://en.wikipedia.org/wiki/Software_release_life_cycle#General_availability_(GA)) (GA for short) usually means the first stable release (excluding prereleases like alpha, beta, rc).

Now it shows:
![image](https://user-images.githubusercontent.com/75155/78327119-ccc7cb00-7584-11ea-8f81-aaf598d0d6cb.png)

For example now for "Vaadin 14.2" the page says that GA was "December 4, 2019 (4 months ago)" which doesn't make sense since there is no 14.2.0 GA release yet but only some alpha releases.

I guess the other dates are also calculated based on first public prerelease? Though I think it would make more sense to calculate all those dates based on the date of the first public stable release (version without a prerelease label like alpha/beta/rc) of the related platform minor. Eg. `14.2.0`, `14.1.0`, `15.0.0`

Imo right now the GA field for 14.2 should be empty (or showing an estimated future date for 14.2.0 release).

**Comment by Haprog** [comment]
Alternatively if there's only a prerelease available, I guess it would be ok to show the first prerelease date in GA column but it should also include some note (maybe with some different color or highlight) that explicitely notes that it's the date of "first prerelease" or something.

**Comment by qtdzz** [comment]
Hi Kari, thank you for creating the issue. Unfortunately, I don't have time and interest in this project anymore. I am going to archive this repository. Please feel free to clone the code if you still find it useful.

Regards,
Tien.
